bash: Move std_cmd_err_handler() before it is used
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/dosab.sh.in b/src/prg/bash/dosab.sh.in
--- a/src/prg/bash/dosab.sh.in
+++ b/src/prg/bash/dosab.sh.in
@@ -71,6 +71,8 @@
 # 05/05/2019	MG	1.1.2	Correct getopt CL for proper quoting.	#
 #				Use eval to process variables which may	#
 #				contain quotes.				#
+# 11/10/2019	MG	1.1.3	Move std_cmd_err_handler() before it is	#
+#				used.					#
 #									#
 #########################################################################
 
@@ -80,7 +82,7 @@
 ##################
 
 readonly outputprefix="$(basename $0):"
-readonly version=1.1.2				# Script version
+readonly version=1.1.3				# Script version
 readonly etclocation=@sysconfdir@/dosab		# Path to etc directory
 readonly packageversion=@pkgversion@		# Package version
 
@@ -102,6 +104,16 @@ Usage is $0 [options]
 EOF
 }
 
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
+std_cmd_err_handler()
+{
+	if (( $1 )); then
+		script_exit $1
+	fi
+}
+
 # Standard function to emit messages depending on various parameters.
 # Parameters -	$1 What:-	The message to emit.
 #		$2 Where:-	stdout == 0
@@ -119,16 +131,6 @@ output()
 	if (( $3 )); then
 		logger "$outputprefix $1"
 		std_cmd_err_handler $?
-	fi
-}
-
-# Standard function to test command error and exit if non-zero.
-# Parameters - $1 is $?
-# No return value.
-std_cmd_err_handler()
-{
-	if (( $1 )); then
-		script_exit $1
 	fi
 }
 
