Standardise error handler function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/dosab.sh.in b/src/prg/bash/dosab.sh.in
--- a/src/prg/bash/dosab.sh.in
+++ b/src/prg/bash/dosab.sh.in
@@ -94,10 +94,12 @@ output()
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
 std_cmd_err_handler()
 {
-	if [ $1 != 0 ]; then
+	if (( $1 )); then
 		script_exit $1
 	fi
 }
